//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ejecicio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estudiante
    {
        public int Id { get; set; }
        public string strNombre { get; set; }
        public string strApellidoP { get; set; }
        public string strApelidoM { get; set; }
        public string strEmail { get; set; }
        public string strGrupo { get; set; }
    }
}
